package com.gzj.express_transportation.entity;

public class Complaint {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaint.c_id
     *
     * @mbg.generated
     */
    private Integer cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaint.waybill_no
     *
     * @mbg.generated
     */
    private String waybillNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaint.kdy_name
     *
     * @mbg.generated
     */
    private String kdyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaint.kh_name
     *
     * @mbg.generated
     */
    private String khName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaint.content
     *
     * @mbg.generated
     */
    private Integer content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaint.c_id
     *
     * @return the value of complaint.c_id
     *
     * @mbg.generated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaint.c_id
     *
     * @param cId the value for complaint.c_id
     *
     * @mbg.generated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaint.waybill_no
     *
     * @return the value of complaint.waybill_no
     *
     * @mbg.generated
     */
    public String getWaybillNo() {
        return waybillNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaint.waybill_no
     *
     * @param waybillNo the value for complaint.waybill_no
     *
     * @mbg.generated
     */
    public void setWaybillNo(String waybillNo) {
        this.waybillNo = waybillNo == null ? null : waybillNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaint.kdy_name
     *
     * @return the value of complaint.kdy_name
     *
     * @mbg.generated
     */
    public String getKdyName() {
        return kdyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaint.kdy_name
     *
     * @param kdyName the value for complaint.kdy_name
     *
     * @mbg.generated
     */
    public void setKdyName(String kdyName) {
        this.kdyName = kdyName == null ? null : kdyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaint.kh_name
     *
     * @return the value of complaint.kh_name
     *
     * @mbg.generated
     */
    public String getKhName() {
        return khName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaint.kh_name
     *
     * @param khName the value for complaint.kh_name
     *
     * @mbg.generated
     */
    public void setKhName(String khName) {
        this.khName = khName == null ? null : khName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaint.content
     *
     * @return the value of complaint.content
     *
     * @mbg.generated
     */
    public Integer getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaint.content
     *
     * @param content the value for complaint.content
     *
     * @mbg.generated
     */
    public void setContent(Integer content) {
        this.content = content;
    }
}