package com.gzj.express_transportation.entity;

public class PersonnelInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personnel_info.p_id
     *
     * @mbg.generated
     */
    private Integer pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personnel_info.p_name
     *
     * @mbg.generated
     */
    private String pName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personnel_info.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personnel_info.birthhday
     *
     * @mbg.generated
     */
    private String birthhday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personnel_info.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personnel_info.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personnel_info.role
     *
     * @mbg.generated
     */
    private String role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personnel_info.p_id
     *
     * @return the value of personnel_info.p_id
     *
     * @mbg.generated
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personnel_info.p_id
     *
     * @param pId the value for personnel_info.p_id
     *
     * @mbg.generated
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personnel_info.p_name
     *
     * @return the value of personnel_info.p_name
     *
     * @mbg.generated
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personnel_info.p_name
     *
     * @param pName the value for personnel_info.p_name
     *
     * @mbg.generated
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personnel_info.sex
     *
     * @return the value of personnel_info.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personnel_info.sex
     *
     * @param sex the value for personnel_info.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personnel_info.birthhday
     *
     * @return the value of personnel_info.birthhday
     *
     * @mbg.generated
     */
    public String getBirthhday() {
        return birthhday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personnel_info.birthhday
     *
     * @param birthhday the value for personnel_info.birthhday
     *
     * @mbg.generated
     */
    public void setBirthhday(String birthhday) {
        this.birthhday = birthhday == null ? null : birthhday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personnel_info.phone
     *
     * @return the value of personnel_info.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personnel_info.phone
     *
     * @param phone the value for personnel_info.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personnel_info.password
     *
     * @return the value of personnel_info.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personnel_info.password
     *
     * @param password the value for personnel_info.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personnel_info.role
     *
     * @return the value of personnel_info.role
     *
     * @mbg.generated
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personnel_info.role
     *
     * @param role the value for personnel_info.role
     *
     * @mbg.generated
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }
}