package com.gzj.express_transportation.entity;

public class Positions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column positions.p_id
     *
     * @mbg.generated
     */
    private Integer pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column positions.waybill_no
     *
     * @mbg.generated
     */
    private String waybillNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column positions.d_position
     *
     * @mbg.generated
     */
    private String dPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column positions.x_position
     *
     * @mbg.generated
     */
    private String xPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column positions.p_time
     *
     * @mbg.generated
     */
    private String pTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column positions.p_id
     *
     * @return the value of positions.p_id
     *
     * @mbg.generated
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column positions.p_id
     *
     * @param pId the value for positions.p_id
     *
     * @mbg.generated
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column positions.waybill_no
     *
     * @return the value of positions.waybill_no
     *
     * @mbg.generated
     */
    public String getWaybillNo() {
        return waybillNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column positions.waybill_no
     *
     * @param waybillNo the value for positions.waybill_no
     *
     * @mbg.generated
     */
    public void setWaybillNo(String waybillNo) {
        this.waybillNo = waybillNo == null ? null : waybillNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column positions.d_position
     *
     * @return the value of positions.d_position
     *
     * @mbg.generated
     */
    public String getdPosition() {
        return dPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column positions.d_position
     *
     * @param dPosition the value for positions.d_position
     *
     * @mbg.generated
     */
    public void setdPosition(String dPosition) {
        this.dPosition = dPosition == null ? null : dPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column positions.x_position
     *
     * @return the value of positions.x_position
     *
     * @mbg.generated
     */
    public String getxPosition() {
        return xPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column positions.x_position
     *
     * @param xPosition the value for positions.x_position
     *
     * @mbg.generated
     */
    public void setxPosition(String xPosition) {
        this.xPosition = xPosition == null ? null : xPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column positions.p_time
     *
     * @return the value of positions.p_time
     *
     * @mbg.generated
     */
    public String getpTime() {
        return pTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column positions.p_time
     *
     * @param pTime the value for positions.p_time
     *
     * @mbg.generated
     */
    public void setpTime(String pTime) {
        this.pTime = pTime == null ? null : pTime.trim();
    }
}