package com.gzj.express_transportation.entity;

public class Waybill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.waybill_no
     *
     * @mbg.generated
     */
    private String waybillNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.weight
     *
     * @mbg.generated
     */
    private String weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.price
     *
     * @mbg.generated
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.kdy_id
     *
     * @mbg.generated
     */
    private String kdyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.kdy_name
     *
     * @mbg.generated
     */
    private String kdyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.kdy_phone
     *
     * @mbg.generated
     */
    private String kdyPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.j_name
     *
     * @mbg.generated
     */
    private String jName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.j_phone
     *
     * @mbg.generated
     */
    private String jPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.j_address
     *
     * @mbg.generated
     */
    private String jAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.s_name
     *
     * @mbg.generated
     */
    private String sName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.s_phone
     *
     * @mbg.generated
     */
    private String sPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.s_address
     *
     * @mbg.generated
     */
    private String sAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.w_status
     *
     * @mbg.generated
     */
    private String wStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.e_id
     *
     * @mbg.generated
     */
    private String eId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.waybill_no
     *
     * @return the value of waybill.waybill_no
     *
     * @mbg.generated
     */
    public String getWaybillNo() {
        return waybillNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.waybill_no
     *
     * @param waybillNo the value for waybill.waybill_no
     *
     * @mbg.generated
     */
    public void setWaybillNo(String waybillNo) {
        this.waybillNo = waybillNo == null ? null : waybillNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.weight
     *
     * @return the value of waybill.weight
     *
     * @mbg.generated
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.weight
     *
     * @param weight the value for waybill.weight
     *
     * @mbg.generated
     */
    public void setWeight(String weight) {
        this.weight = weight == null ? null : weight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.price
     *
     * @return the value of waybill.price
     *
     * @mbg.generated
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.price
     *
     * @param price the value for waybill.price
     *
     * @mbg.generated
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.kdy_id
     *
     * @return the value of waybill.kdy_id
     *
     * @mbg.generated
     */
    public String getKdyId() {
        return kdyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.kdy_id
     *
     * @param kdyId the value for waybill.kdy_id
     *
     * @mbg.generated
     */
    public void setKdyId(String kdyId) {
        this.kdyId = kdyId == null ? null : kdyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.kdy_name
     *
     * @return the value of waybill.kdy_name
     *
     * @mbg.generated
     */
    public String getKdyName() {
        return kdyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.kdy_name
     *
     * @param kdyName the value for waybill.kdy_name
     *
     * @mbg.generated
     */
    public void setKdyName(String kdyName) {
        this.kdyName = kdyName == null ? null : kdyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.kdy_phone
     *
     * @return the value of waybill.kdy_phone
     *
     * @mbg.generated
     */
    public String getKdyPhone() {
        return kdyPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.kdy_phone
     *
     * @param kdyPhone the value for waybill.kdy_phone
     *
     * @mbg.generated
     */
    public void setKdyPhone(String kdyPhone) {
        this.kdyPhone = kdyPhone == null ? null : kdyPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.j_name
     *
     * @return the value of waybill.j_name
     *
     * @mbg.generated
     */
    public String getjName() {
        return jName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.j_name
     *
     * @param jName the value for waybill.j_name
     *
     * @mbg.generated
     */
    public void setjName(String jName) {
        this.jName = jName == null ? null : jName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.j_phone
     *
     * @return the value of waybill.j_phone
     *
     * @mbg.generated
     */
    public String getjPhone() {
        return jPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.j_phone
     *
     * @param jPhone the value for waybill.j_phone
     *
     * @mbg.generated
     */
    public void setjPhone(String jPhone) {
        this.jPhone = jPhone == null ? null : jPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.j_address
     *
     * @return the value of waybill.j_address
     *
     * @mbg.generated
     */
    public String getjAddress() {
        return jAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.j_address
     *
     * @param jAddress the value for waybill.j_address
     *
     * @mbg.generated
     */
    public void setjAddress(String jAddress) {
        this.jAddress = jAddress == null ? null : jAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.s_name
     *
     * @return the value of waybill.s_name
     *
     * @mbg.generated
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.s_name
     *
     * @param sName the value for waybill.s_name
     *
     * @mbg.generated
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.s_phone
     *
     * @return the value of waybill.s_phone
     *
     * @mbg.generated
     */
    public String getsPhone() {
        return sPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.s_phone
     *
     * @param sPhone the value for waybill.s_phone
     *
     * @mbg.generated
     */
    public void setsPhone(String sPhone) {
        this.sPhone = sPhone == null ? null : sPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.s_address
     *
     * @return the value of waybill.s_address
     *
     * @mbg.generated
     */
    public String getsAddress() {
        return sAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.s_address
     *
     * @param sAddress the value for waybill.s_address
     *
     * @mbg.generated
     */
    public void setsAddress(String sAddress) {
        this.sAddress = sAddress == null ? null : sAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.w_status
     *
     * @return the value of waybill.w_status
     *
     * @mbg.generated
     */
    public String getwStatus() {
        return wStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.w_status
     *
     * @param wStatus the value for waybill.w_status
     *
     * @mbg.generated
     */
    public void setwStatus(String wStatus) {
        this.wStatus = wStatus == null ? null : wStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.e_id
     *
     * @return the value of waybill.e_id
     *
     * @mbg.generated
     */
    public String geteId() {
        return eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.e_id
     *
     * @param eId the value for waybill.e_id
     *
     * @mbg.generated
     */
    public void seteId(String eId) {
        this.eId = eId == null ? null : eId.trim();
    }
}